### ISSUE TITLE
log4j config, how to add custom appender

### ISSUE THREAD

**Issue by bilsch** [voxpupuli/puppet-elasticsearch#529]
We are looking to add a modification to the log4j appender type used to get the rolling file appender vs the daily rolling file appender.

http://grokbase.com/t/gg/elasticsearch/14chrn08rj/pruning-logs-how-to-get-maxbackupindex-to-work

From what I see in the [template](https://github.com/elastic/puppet-elasticsearch/blob/master/templates/etc/elasticsearch/logging.yml.erb#L13-L15) the only change we can make is to alter the already-configured appender. Is that right?

Is there a way to inject a modified appender via hiera? I'm not sure if this is the right yml structure for hieradata but this is what I came up with to try out/test:

```
    logging_config:
      rollingFile:
        file:
          type: rollingFile
          file: "${path.logs}/${cluster.name}.log"
          maxBackupIndex: 10
          layout:
            type: pattern
            conversionPattern: '"[%d{ISO8601}][%-5p][%-25c] %m%n"'
```

Not sure if the nested yml structure is the right way to go. The elasticsearch.yml renders something like `file.type: rollingFile` instead
